//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCommunityBuilder.Client.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCommunityBuilder.Client.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag_en.png.
        /// </summary>
        public static string _1033 {
            get {
                return ResourceManager.GetString("1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag_es.png.
        /// </summary>
        public static string _2058 {
            get {
                return ResourceManager.GetString("2058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Ready for Investment Crowd- funding? Take Our Readiness Survey..
        /// </summary>
        public static string AreyouReadyforInvestmentCrowdfunding_TakeOurReadinessSurvey_ {
            get {
                return ResourceManager.GetString("AreyouReadyforInvestmentCrowdfunding?TakeOurReadinessSurvey.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to websurveyc3.png.
        /// </summary>
        public static string AreyouReadyforInvestmentCrowdfundingImage {
            get {
                return ResourceManager.GetString("AreyouReadyforInvestmentCrowdfundingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:5002/upload/images/.
        /// </summary>
        public static string BaseImageUrl {
            get {
                return ResourceManager.GetString("BaseImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a fan favorite and get a whole week in the spotlight..
        /// </summary>
        public static string Becomeafanfavoriteandgetawholeweekinthespotlight_ {
            get {
                return ResourceManager.GetString("Becomeafanfavoriteandgetawholeweekinthespotlight.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business of the Week:.
        /// </summary>
        public static string BOWcol {
            get {
                return ResourceManager.GetString("BOWcol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Businesses.
        /// </summary>
        public static string Businesses {
            get {
                return ResourceManager.GetString("Businesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Businesses Discussing Crowdfunding Options:.
        /// </summary>
        public static string BusinessesDiscussingCrowdfundingOptions {
            get {
                return ResourceManager.GetString("BusinessesDiscussingCrowdfundingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lcu.jpg.
        /// </summary>
        public static string BusinessMainImage {
            get {
                return ResourceManager.GetString("BusinessMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business of the Week:.
        /// </summary>
        public static string BusinessoftheWeek {
            get {
                return ResourceManager.GetString("BusinessoftheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f04b8ea7-1553-4b6d-8094-ab6518866ae1.PNG.
        /// </summary>
        public static string BusinessoftheWeekImage {
            get {
                return ResourceManager.GetString("BusinessoftheWeekImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSAKI.PNG.
        /// </summary>
        public static string CatererImage {
            get {
                return ResourceManager.GetString("CatererImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Offerings.
        /// </summary>
        public static string CurrentOfferings {
            get {
                return ResourceManager.GetString("CurrentOfferings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Offerings from Las Cruces Businesses.
        /// </summary>
        public static string CurrentOfferingsfromLasCrucesBusinesses {
            get {
                return ResourceManager.GetString("CurrentOfferingsfromLasCrucesBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t just buy local, invest local. Here&apos;s how:.
        /// </summary>
        public static string DontjustbuylocalinvestlocalHereshow {
            get {
                return ResourceManager.GetString("DontjustbuylocalinvestlocalHereshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event of the Week:.
        /// </summary>
        public static string EOWcol {
            get {
                return ResourceManager.GetString("EOWcol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanEvent.jpg.
        /// </summary>
        public static string EventMainImage {
            get {
                return ResourceManager.GetString("EventMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event of the Week:.
        /// </summary>
        public static string EventoftheWeek {
            get {
                return ResourceManager.GetString("EventoftheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans.
        /// </summary>
        public static string Fans {
            get {
                return ResourceManager.GetString("Fans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMbusinessw.png.
        /// </summary>
        public static string FansMainImage {
            get {
                return ResourceManager.GetString("FansMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Complete List of SmallStreet Businesses.
        /// </summary>
        public static string FindaCompleteListofSmallStreetBusinesses {
            get {
                return ResourceManager.GetString("FindaCompleteListofSmallStreetBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your favorite business.
        /// </summary>
        public static string Findyourfavoritebusiness {
            get {
                return ResourceManager.GetString("Findyourfavoritebusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five Ways You Can Become a Champion Local Investor:.
        /// </summary>
        public static string FiveWaysYouCanBecomeaChampionLocalInvestor_ {
            get {
                return ResourceManager.GetString("FiveWaysYouCanBecomeaChampionLocalInvestor:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3953fed5-24a3-4090-b1b4-c2fe63f84df5.PNG.
        /// </summary>
        public static string GroceriesImage {
            get {
                return ResourceManager.GetString("GroceriesImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rodeo3sm.jpg.
        /// </summary>
        public static string IndexMainImage {
            get {
                return ResourceManager.GetString("IndexMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LasCrucesHousingStrategy.jpg.
        /// </summary>
        public static string InvestorMainImage {
            get {
                return ResourceManager.GetString("InvestorMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investors.
        /// </summary>
        public static string Investors {
            get {
                return ResourceManager.GetString("Investors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lcnm2.PNG.
        /// </summary>
        public static string LasCruseSliderImage1 {
            get {
                return ResourceManager.GetString("LasCruseSliderImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lascruces.jpg.
        /// </summary>
        public static string LasCruseSliderImage2 {
            get {
                return ResourceManager.GetString("LasCruseSliderImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las-Cruces-NM.jpg.
        /// </summary>
        public static string LasCruseSliderImage3 {
            get {
                return ResourceManager.GetString("LasCruseSliderImage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osaki.png.
        /// </summary>
        public static string LocalBusinessImage {
            get {
                return ResourceManager.GetString("LocalBusinessImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More for Business.
        /// </summary>
        public static string MoreforBusiness {
            get {
                return ResourceManager.GetString("MoreforBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More for Fans.
        /// </summary>
        public static string MoreforFans {
            get {
                return ResourceManager.GetString("MoreforFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More for Investors.
        /// </summary>
        public static string MoreforInvestors {
            get {
                return ResourceManager.GetString("MoreforInvestors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offering of the Week:.
        /// </summary>
        public static string OfferingoftheWeek {
            get {
                return ResourceManager.GetString("OfferingoftheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cassava.png.
        /// </summary>
        public static string OfferingoftheWeekImage {
            get {
                return ResourceManager.GetString("OfferingoftheWeekImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offering of the Week:.
        /// </summary>
        public static string OOWcol {
            get {
                return ResourceManager.GetString("OOWcol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or invite a business to register.
        /// </summary>
        public static string orinviteabusinesstoregister {
            get {
                return ResourceManager.GetString("orinviteabusinesstoregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Deals.
        /// </summary>
        public static string PurchasingDeals {
            get {
                return ResourceManager.GetString("PurchasingDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Your Dollars to Work.
        /// </summary>
        public static string PutYourDollars {
            get {
                return ResourceManager.GetString("PutYourDollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Your Dollars to Work.
        /// </summary>
        public static string PutYourDollarstoWork {
            get {
                return ResourceManager.GetString("PutYourDollarstoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Fans Get the Following Benefits:.
        /// </summary>
        public static string RegisteredFansGettheFollowingBenefits {
            get {
                return ResourceManager.GetString("RegisteredFansGettheFollowingBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page_Index/discuss.jpg.
        /// </summary>
        public static string ResourceConversationImage {
            get {
                return ResourceManager.GetString("ResourceConversationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lem.png.
        /// </summary>
        public static string ResourceEffectImage {
            get {
                return ResourceManager.GetString("ResourceEffectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lchssm.jpg.
        /// </summary>
        public static string ResourceMainImage {
            get {
                return ResourceManager.GetString("ResourceMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 86ecd0dd-c18c-4462-b1fb-7dbadda9da57.PNG.
        /// </summary>
        public static string ScreenPrintingImage {
            get {
                return ResourceManager.GetString("ScreenPrintingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.png.
        /// </summary>
        public static string SearchImage {
            get {
                return ResourceManager.GetString("SearchImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL.gif.
        /// </summary>
        public static string SpecialOfferImage {
            get {
                return ResourceManager.GetString("SpecialOfferImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strengthen your business by converting customers into fans. Here&apos;s how you benefit:.
        /// </summary>
        public static string StrengthenyourbusinessbyconvertingcustomersintofansHerehowyoubenefit {
            get {
                return ResourceManager.GetString("StrengthenyourbusinessbyconvertingcustomersintofansHerehowyoubenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 956a22cf-9a3a-437f-9ac0-d474ec4114c5.PNG.
        /// </summary>
        public static string TherapeuticImage {
            get {
                return ResourceManager.GetString("TherapeuticImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do Businesses say?.
        /// </summary>
        public static string WhatdoBusinessessay_ {
            get {
                return ResourceManager.GetString("WhatdoBusinessessay?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bugy.PNG.
        /// </summary>
        public static string WhatdoBusinessessayImage {
            get {
                return ResourceManager.GetString("WhatdoBusinessessayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do Fans say?.
        /// </summary>
        public static string WhatdoFanssay_ {
            get {
                return ResourceManager.GetString("WhatdoFanssay?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30hispanicsm.jfif.
        /// </summary>
        public static string WhatdoFanssayImage {
            get {
                return ResourceManager.GetString("WhatdoFanssayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do Investors say?.
        /// </summary>
        public static string WhatdoInvestorssay_ {
            get {
                return ResourceManager.GetString("WhatdoInvestorssay?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55yroldsm.jfif.
        /// </summary>
        public static string WhatdoInvestorssayImage {
            get {
                return ResourceManager.GetString("WhatdoInvestorssayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who&apos;s Winning the Race For Fans?.
        /// </summary>
        public static string WhoWinningtheRaceForFans_ {
            get {
                return ResourceManager.GetString("WhoWinningtheRaceForFans?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOrseraceb.png.
        /// </summary>
        public static string WhoWinningtheRaceForFansImage {
            get {
                return ResourceManager.GetString("WhoWinningtheRaceForFansImage", resourceCulture);
            }
        }
    }
}
